/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.Tour;
import Dao.Ve;
import controller.DAOtour;
import controller.DAOve;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quang
 */
public class DSTour extends javax.swing.JFrame {

    /**
     * Creates new form DSTour
     */
    private final String[] header = {"Mã Tour", "Tên Tour", "Ngày khởi hành", "Thời lượng", "Giá"};
    private ArrayList<Tour> list = new ArrayList<>();
    private DefaultTableModel model;

    public DSTour() {
        initComponents();
        btnDat.setEnabled(false);
        btnXemChiTiet.setEnabled(false);
        model = (DefaultTableModel) tblDSchuyenbay.getModel();
        model.setColumnIdentifiers(header);

    }
    public void showTable(ArrayList<Tour> items) {
        model.setRowCount(0);
        for (Tour item : items) {
            model.addRow(new Object[]{
               item.getMaTour(), item.getTenTour(), item.getNgayKH(), item.getThoiLuong(), item.getGia()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSchuyenbay = new javax.swing.JTable();
        btnDat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbtour1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbtour2 = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbGioiThieu = new javax.swing.JLabel();
        btnXemChiTiet = new javax.swing.JButton();
        lbKH = new javax.swing.JLabel();
        lbDD1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGioiThieu = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDSchuyenbay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDSchuyenbay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSchuyenbayMouseClicked(evt);
            }
        });
        tblDSchuyenbay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblDSchuyenbayKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSchuyenbay);

        btnDat.setText("Đặt");
        btnDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Danh sách Tour");

        lbtour1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbtour1.setText("Tour1");

        jLabel3.setText("-");

        lbtour2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbtour2.setText("Tour 2");

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Giới Thiệu Tour:");

        lbGioiThieu.setText(".");

        btnXemChiTiet.setText("Xem chi tiết tour");
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });

        lbKH.setFont(new java.awt.Font("Tahoma", 2, 9)); // NOI18N
        lbKH.setText("jLabel4");

        lbDD1.setFont(new java.awt.Font("Tahoma", 2, 9)); // NOI18N
        lbDD1.setText("jLabel5");

        txtGioiThieu.setColumns(20);
        txtGioiThieu.setRows(5);
        txtGioiThieu.setText("Mời Quý khách chọn Tour! \nWelcome!");
        jScrollPane2.setViewportView(txtGioiThieu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbtour1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(lbKH))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbtour2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDD1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(btnDat, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbGioiThieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lbtour1)
                    .addComponent(jLabel3)
                    .addComponent(lbtour2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lbGioiThieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbKH)
                            .addComponent(lbDD1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void settittle(String kh, String dd, String lbkh, String lbDD) {
        lbtour1.setText(kh);
        lbtour2.setText(dd);
        lbKH.setText(lbkh);
        lbDD1.setText(lbDD);
    }

    
    private void btnDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatActionPerformed
        // TODO add your handling code here:
        DangKyTour dk = new DangKyTour();

        int val = JOptionPane.showConfirmDialog(rootPane, "Xác nhận đặt vé", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (val == JOptionPane.YES_OPTION) {
            dk.show();
            this.setVisible(false);
            ArrayList<Ve> listVe = new ArrayList<Ve>();
            listVe = new DAOve().getListVe();
            int x = tblDSchuyenbay.getSelectedRow();
            String mt = tblDSchuyenbay.getValueAt(x, 0).toString();
            int i = listVe.size() + 1;
            String mv = "Ve" + i + "";
            dk.setMa(mt);
        }
    }//GEN-LAST:event_btnDatActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        try {
            // TODO add your handling code here:
            SearchTour sr = new SearchTour();
            this.setVisible(false);
            sr.show();
        } catch (Exception ex) {
            Logger.getLogger(DSTour.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnHuyActionPerformed

    private void tblDSchuyenbayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDSchuyenbayKeyPressed
        // TODO add your handling code here:
        btnDat.setEnabled(true);
    }//GEN-LAST:event_tblDSchuyenbayKeyPressed

    private void tblDSchuyenbayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSchuyenbayMouseClicked
        // TODO add your handling code here:
        btnDat.setEnabled(true);
        btnXemChiTiet.setEnabled(true);
        list = new DAOtour().searchTour(lbKH.getText().trim(), lbDD1.getText().trim());
        int a = tblDSchuyenbay.getSelectedRow();
        txtGioiThieu.setText(list.get(a).getGioiThieuTour());
        System.out.println(list.get(a).getGioiThieuTour());
        System.out.println(list.get(a).getDichVu());
    }//GEN-LAST:event_tblDSchuyenbayMouseClicked

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiTietActionPerformed
        // TODO add your handling code here:
        ChiTietTour ct = new ChiTietTour();
        list = new DAOtour().searchTour(lbKH.getText().trim(), lbDD1.getText().trim());
        int a = tblDSchuyenbay.getSelectedRow();
        ct.show();
//        ct.settittle(list.get(a).getDichVu(), list.get(a).getLichTrinhTour(), list.get(a).getChiTietLichTrinh());
    }//GEN-LAST:event_btnXemChiTietActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSTour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXemChiTiet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDD1;
    private javax.swing.JLabel lbGioiThieu;
    private javax.swing.JLabel lbKH;
    private javax.swing.JLabel lbtour1;
    private javax.swing.JLabel lbtour2;
    private javax.swing.JTable tblDSchuyenbay;
    private javax.swing.JTextArea txtGioiThieu;
    // End of variables declaration//GEN-END:variables
}
