/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminForm;

import Dao.DiaDiem;
import Dao.Tour;
import controller.DAOdiaDiem;
import controller.DAOtour;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import validate.Validator;

/**
 *
 * @author nvta1
 */
public class QuanLyTour extends javax.swing.JFrame {

    private final String[] header = {"STT", "Mã Tour", "Tên Tour", "Ngày Khời Hành", "Thời Lượng", "Nơi Khởi Hành", "Nơi Đến", "Giá"};
    private ArrayList<Tour> items = new ArrayList<>();
    private int selectedIndex;
    private DefaultTableModel model;

    /**
     * Creates new form QuanLyTour
     */
    public QuanLyTour() {
        initComponents();
        model = (DefaultTableModel) tbQuanLyTour.getModel();
        model.setColumnIdentifiers(header);
        showTable();
    }

    public void showTable() {
        items = new DAOtour().getListTour();
        model.setRowCount(0);
        for (Tour item : items) {
            model.addRow(new Object[]{
                model.getRowCount() + 1, item.getMaTour(), item.getTenTour(), item.getNgayKH(), item.getThoiLuong(), item.getNoiKH(), item.getNoiDen(), item.getGia()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlable6 = new javax.swing.JLabel();
        txtNoiKH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaTour = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenTour = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQuanLyTour = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtNgayKH = new javax.swing.JTextField();
        btnThoai = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtThoiLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNoiDen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlable6.setText("Nơi KH");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Quản Lý Tour");

        jLabel2.setText("Mã tour");

        jLabel3.setText("Tên tour");

        jLabel4.setText("Ngày KH");

        tbQuanLyTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbQuanLyTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbQuanLyTourMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbQuanLyTour);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoai.setText("Thoát");

        jLabel5.setText("Thời lượng");

        jLabel6.setText("Nơi đến");

        jLabel7.setText("Giá");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenTour, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txtGia))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtThoiLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txtNgayKH))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlable6)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoiDen, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClear)
                        .addGap(99, 99, 99)
                        .addComponent(btnThem)
                        .addGap(121, 121, 121)
                        .addComponent(btnSua)
                        .addGap(106, 106, 106)
                        .addComponent(btnXoa)
                        .addGap(109, 109, 109)
                        .addComponent(btnThoai)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgayKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlable6)
                    .addComponent(txtNoiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNoiDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnThoai)
                    .addComponent(btnThem)
                    .addComponent(btnClear))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void ClearTxt() {
        txtMaTour.setText("");
        txtTenTour.setText("");
        txtNgayKH.setText("");
        txtThoiLuong.setText("");
        txtNoiKH.setText("");
        txtNoiDen.setText("");
        txtGia.setText("");
    }
    private void tbQuanLyTourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQuanLyTourMouseClicked
        // TODO add your handling code here:
        int row = tbQuanLyTour.getSelectedRow();
        txtMaTour.setText(model.getValueAt(row, 1).toString());
        txtTenTour.setText(model.getValueAt(row, 2).toString());
        txtNgayKH.setText(model.getValueAt(row, 3).toString());
        txtThoiLuong.setText(model.getValueAt(row, 4).toString());
        txtNoiKH.setText(model.getValueAt(row, 5).toString());
        txtNoiDen.setText(model.getValueAt(row, 6).toString());
        txtGia.setText(model.getValueAt(row, 7).toString());

    }//GEN-LAST:event_tbQuanLyTourMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        ClearTxt();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        boolean isSuccess = true;
       
        ArrayList<Validator> data = new ArrayList<>();
        Validator maTour = new Validator(txtMaTour.getText(), new String[]{"required"}, "Ma Tour"),
                tenTour = new Validator(txtTenTour.getText(), new String[]{"required", "isString"}, "Ten Tour"),
                ngayKH = new Validator(txtNgayKH.getText(), new String[]{"required"}, "Ngay Khoi Hanh"),
                thoiLuong = new Validator(txtThoiLuong.getText(), new String[]{"required","isInteger"}, "Thoi Luong"),
                noiKH = new Validator(txtNoiKH.getText(), new String[]{"required"}, "Noi Khoi Hanh"),
                noiDen = new Validator(txtNoiDen.getText(), new String[]{"required"}, "Noi Den"),
                gia = new Validator(txtGia.getText(), new String[]{"required","isInteger"}, "Gia");
         try {
            Date ngayKH1 = new SimpleDateFormat("dd/MM/yyyy").parse(txtNgayKH.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Ngày sinh phải đúng định dạng dd/MM/yyyy");
            isSuccess = false;
        }
        data.add(maTour);
        data.add(tenTour);
        data.add(ngayKH);
        data.add(thoiLuong);
        data.add(noiKH);
        data.add(noiDen);
        data.add(gia);
        for (Validator s : data) {
            if (!s.setTextField(this)) {
                isSuccess = false;
            }
        }
        if (isSuccess) {
            Tour item = new Tour(maTour.getText(), tenTour.getText(),ngayKH.getText(),Integer.parseInt(thoiLuong.getText()),noiKH.getText().toUpperCase(),noiDen.getText().toUpperCase(),gia.getText());
            if (new DAOtour().addItem(item)) {
                this.showTable();
                JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
                ClearTxt();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm mới thất bại!");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
          boolean isSuccess = true;
       
        ArrayList<Validator> data = new ArrayList<>();
        Validator maTour = new Validator(txtMaTour.getText(), new String[]{"required"}, "Ma Tour"),
                tenTour = new Validator(txtTenTour.getText(), new String[]{"required", "isString"}, "Ten Tour"),
                ngayKH = new Validator(txtNgayKH.getText(), new String[]{"required"}, "Ngay Khoi Hanh"),
                thoiLuong = new Validator(txtThoiLuong.getText(), new String[]{"required","isInteger"}, "Thoi Luong"),
                noiKH = new Validator(txtNoiKH.getText(), new String[]{"required"}, "Noi Khoi Hanh"),
                noiDen = new Validator(txtNoiDen.getText(), new String[]{"required"}, "Noi Den"),
                gia = new Validator(txtGia.getText().trim(), new String[]{"required","isInteger"}, "Gia");
         try {
            Date ngayKH1 = new SimpleDateFormat("yyyy-dd-MM").parse(txtNgayKH.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Ngày sinh phải đúng định dạng yyyy-dd-MM");
            isSuccess = false;
        }
        data.add(maTour);
        data.add(tenTour);
        data.add(ngayKH);
        data.add(thoiLuong);
        data.add(noiKH);
        data.add(noiDen);
        data.add(gia);
        for (Validator s : data) {
            if (!s.setTextField(this)) {
                isSuccess = false;
            }
        }
        if (isSuccess) {
            Tour item = new Tour(maTour.getText(), tenTour.getText(),ngayKH.getText(),Integer.parseInt(thoiLuong.getText()),noiKH.getText().toUpperCase(),noiDen.getText().toUpperCase(),gia.getText());
            if (new DAOtour().UpdateItem(item)) {
                this.showTable();
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
                ClearTxt();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa Thất bại");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
          Tour item = new Tour(txtMaTour.getText(), null, null, ALLBITS, null, null, null);
        if (new DAOtour().DeleteItem(item)) {
            this.showTable();
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
        }
        else
            JOptionPane.showMessageDialog(this, "Không xóa được");
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyTour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoai;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlable6;
    private javax.swing.JTable tbQuanLyTour;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaTour;
    private javax.swing.JTextField txtNgayKH;
    private javax.swing.JTextField txtNoiDen;
    private javax.swing.JTextField txtNoiKH;
    private javax.swing.JTextField txtTenTour;
    private javax.swing.JTextField txtThoiLuong;
    // End of variables declaration//GEN-END:variables
}
