/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminForm;

import Dao.DiaDiem;
import Dao.Tour;
import controller.DAOdiaDiem;
import controller.DAOtour;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import validate.Validator;

/**
 *
 * @author nvta1
 */
public class QuanLyTour extends javax.swing.JFrame {

    private final String[] header = {"STT", "Mã Tour", "Tên Tour", "Ngày Khời Hành", "Thời Lượng", "Nơi Khởi Hành", "Nơi Đến", "Giá"};
    private ArrayList<Tour> items = new ArrayList<>();
    private int selectedIndex;
    private DefaultTableModel model;

    /**
     * Creates new form QuanLyTour
     */
    public QuanLyTour() {
        initComponents();
        model = (DefaultTableModel) tbQuanLyTour.getModel();
        model.setColumnIdentifiers(header);
        showTable();
    }

    public void showTable() {
        items = new DAOtour().getListTour();
        model.setRowCount(0);
        for (Tour item : items) {
            model.addRow(new Object[]{
                model.getRowCount() + 1, item.getMaTour(), item.getTenTour(), item.getNgayKH(), item.getThoiLuong(), item.getNoiKH(), item.getNoiDen(), item.getGia()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlable6 = new javax.swing.JLabel();
        txtNoiKH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaTour = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenTour = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQuanLyTour = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtNgayKH = new javax.swing.JTextField();
        btnThoai = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtThoiLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNoiDen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtLichTrinh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDichVu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtGioiThieuTour = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtKhuyenMai = new javax.swing.JTextField();
        txtChiTietLichTrinh = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlable6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlable6.setText("Nơi KH");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Quản Lý Tour");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mã tour");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tên tour");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Ngày KH");

        tbQuanLyTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbQuanLyTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbQuanLyTourMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbQuanLyTour);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoai.setText("Thoát");
        btnThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoaiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Thời lượng");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nơi đến");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Giá / Người");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Lịch Trình");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Chi tiết lịch trình");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Dịch Vụ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Giới Thiệu Tour");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Khuyến Mãi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGia, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(txtTenTour)
                            .addComponent(txtMaTour)
                            .addComponent(txtDichVu))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel8))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayKH)
                            .addComponent(txtThoiLuong)
                            .addComponent(txtLichTrinh)
                            .addComponent(txtGioiThieuTour, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlable6)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoiDen, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChiTietLichTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(303, 303, 303)))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgayKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlable6)
                    .addComponent(txtNoiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNoiDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtLichTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtChiTietLichTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtGioiThieuTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void ClearText() {
        txtMaTour.setText("");
        txtTenTour.setText("");
        txtNgayKH.setText("");
        txtThoiLuong.setText("");
        txtNoiKH.setText("");
        txtNoiDen.setText("");
        txtGia.setText("");
    }
    private void tbQuanLyTourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQuanLyTourMouseClicked
        // TODO add your handling code here:
        int row = tbQuanLyTour.getSelectedRow();
        txtMaTour.setText(model.getValueAt(row, 1).toString());
        txtTenTour.setText(model.getValueAt(row, 2).toString());
        txtNgayKH.setText(model.getValueAt(row, 3).toString());
        txtThoiLuong.setText(model.getValueAt(row, 4).toString());
        txtNoiKH.setText(model.getValueAt(row, 5).toString());
        txtNoiDen.setText(model.getValueAt(row, 6).toString());
        txtGia.setText(model.getValueAt(row, 7).toString());

    }//GEN-LAST:event_tbQuanLyTourMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        ClearText();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        boolean isSuccess = true;

        ArrayList<Validator> data = new ArrayList<>();
        Validator maTour = new Validator(txtMaTour.getText(), new String[]{"required"}, "Mã Tour"),
                tenTour = new Validator(txtTenTour.getText(), new String[]{"required", "isString"}, "Tên Tour"),
                ngayKH = new Validator(txtNgayKH.getText(), new String[]{"required"}, "Ngày khởi hành"),
                thoiLuong = new Validator(txtThoiLuong.getText(), new String[]{"required", "isInteger"}, "Thời lượng"),
                noiKH = new Validator(txtNoiKH.getText(), new String[]{"required"}, "Nơi khởi hành"),
                noiDen = new Validator(txtNoiDen.getText(), new String[]{"required"}, "Nơi đến"),
                gia = new Validator(txtGia.getText(), new String[]{"required", "isInteger"}, "Giá"),
                LichTrinhTour = new Validator(txtLichTrinh.getText(), new String[]{"required"}, "Lịch Trình"),
                ChiTietLichTrinh = new Validator(txtChiTietLichTrinh.getText(), new String[]{"required"}, "Lịch Trình"),
                DichVu = new Validator(txtDichVu.getText(), new String[]{"required"}, "Lịch Trình"),
                GioiThieuTour = new Validator(txtGioiThieuTour.getText(), new String[]{"required"}, "Lịch Trình"),
                KhuyenMai = new Validator(txtKhuyenMai.getText(), new String[]{"required"}, "Lịch Trình");

        try {
            Date ngayKH1 = new SimpleDateFormat("dd/MM/yyyy").parse(txtNgayKH.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Ngày khởi hành phải đúng định dạng dd/MM/yyyy");
            isSuccess = false;
        }
        data.add(maTour);
        data.add(tenTour);
        data.add(ngayKH);
        data.add(thoiLuong);
        data.add(noiKH);
        data.add(noiDen);
        data.add(gia);
        data.add(LichTrinhTour);
        data.add(ChiTietLichTrinh);
        data.add(DichVu);
        data.add(GioiThieuTour);
        data.add(KhuyenMai);

        for (Validator s : data) {
            if (!s.setTextField(this)) {
                isSuccess = false;
            }
        }
        if (isSuccess) {
            Tour item = new Tour(maTour.getText(), tenTour.getText(), ngayKH.getText(), Integer.parseInt(thoiLuong.getText()), noiKH.getText().toUpperCase(), noiDen.getText().toUpperCase(), gia.getText(),LichTrinhTour.getText());
            if (new DAOtour().addItem(item)) {
                this.showTable();
                JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
                ClearText();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm mới thất bại!");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        boolean isSuccess = true;

        ArrayList<Validator> data = new ArrayList<>();
        Validator maTour = new Validator(txtMaTour.getText(), new String[]{"required"}, "Mã Tour"),
                tenTour = new Validator(txtTenTour.getText(), new String[]{"required", "isString"}, "Tên Tour"),
                ngayKH = new Validator(txtNgayKH.getText(), new String[]{"required"}, "Ngày khởi hành"),
                thoiLuong = new Validator(txtThoiLuong.getText(), new String[]{"required", "isInteger"}, "Thời lượng"),
                noiKH = new Validator(txtNoiKH.getText(), new String[]{"required"}, "Nơi khởi hành"),
                noiDen = new Validator(txtNoiDen.getText(), new String[]{"required"}, "Nơi đến"),
                gia = new Validator(txtGia.getText().trim(), new String[]{"required", "isInteger"}, "Giá");
        try {
            Date ngayKH1 = new SimpleDateFormat("yyyy-dd-MM").parse(txtNgayKH.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Ngày khởi hành phải đúng định dạng yyyy-dd-MM");
            isSuccess = false;
        }
        data.add(maTour);
        data.add(tenTour);
        data.add(ngayKH);
        data.add(thoiLuong);
        data.add(noiKH);
        data.add(noiDen);
        data.add(gia);
        for (Validator s : data) {
            if (!s.setTextField(this)) {
                isSuccess = false;
            }
        }
        if (isSuccess) {
            Tour item = new Tour(maTour.getText(), tenTour.getText(), ngayKH.getText(), Integer.parseInt(thoiLuong.getText()), noiKH.getText().toUpperCase(), noiDen.getText().toUpperCase(), gia.getText());
            if (new DAOtour().UpdateItem(item)) {
                this.showTable();
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
                ClearText();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa Thất bại");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        Tour item = new Tour(txtMaTour.getText(), null, null, ALLBITS, null, null, null);
        if (new DAOtour().DeleteItem(item)) {
            this.showTable();
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
            ClearText();
        } else {
            JOptionPane.showMessageDialog(this, "Không xóa được");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoaiActionPerformed
        // TODO add your handling code here:
        MenuQuanLy a = new MenuQuanLy();
        a.show();
        this.dispose();
    }//GEN-LAST:event_btnThoaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyTour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoai;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlable6;
    private javax.swing.JTable tbQuanLyTour;
    private javax.swing.JTextField txtChiTietLichTrinh;
    private javax.swing.JTextField txtDichVu;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtGioiThieuTour;
    private javax.swing.JTextField txtKhuyenMai;
    private javax.swing.JTextField txtLichTrinh;
    private javax.swing.JTextField txtMaTour;
    private javax.swing.JTextField txtNgayKH;
    private javax.swing.JTextField txtNoiDen;
    private javax.swing.JTextField txtNoiKH;
    private javax.swing.JTextField txtTenTour;
    private javax.swing.JTextField txtThoiLuong;
    // End of variables declaration//GEN-END:variables
}
